# -*- coding: utf-8 -*-
"""stock_hunter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAtgAhJbcvYA0NhT3_EGdAVbl3dS_nCB
"""

import os
import requests
import pandas as pd
import datetime
import time
import yfinance as yf

# ================= 參數與金鑰設定 =================
# 從 GitHub Secrets 讀取金鑰，避免外洩
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "8235550528:AAF9VFnKcSj6O9TwIJ8weEOPsQHSmhOwd2A")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "-1003855409059")
FINMIND_TOKEN = os.getenv("FINMIND_TOKEN", "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYWZvcnR1bmFkbyIsImVtYWlsIjoiYWZvcnR1bmFkby5mdUBnbWFpbC5jb20ifQ._N8Ej3fx-n48ue-5DFB60yAkGXmwTwswyqSIsJZ0vgc")

CONSECUTIVE_DAYS = 3
MAX_COST_DEVIATION = 1.05

def send_telegram_message(msg):
    url = f"https://api.telegram.org/bot/8235550528:AAF9VFnKcSj6O9TwIJ8weEOPsQHSmhOwd2A/sendMessage"
    requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": msg, "parse_mode": "Markdown", "disable_web_page_preview": True})

# ================= 台股分析模組 =================
def get_twse_dates(days=5):
    dates = []
    today = datetime.date.today()
    while len(dates) < days:
        if today.weekday() < 5:
            dates.append(today)
        today -= datetime.timedelta(days=1)
    return dates[::-1]

def get_twse_buy(date_str):
    url = f"https://www.twse.com.tw/fund/T86?response=json&date={date_str}&selectType=ALL"
    try:
        res = requests.get(url, headers={'User-agent': 'Mozilla/5.0'})
        data = res.json()
        if data['stat'] == 'OK':
            df = pd.DataFrame(data['data'], columns=data['fields'])
            df['三大法人買賣超股數'] = df['三大法人買賣超股數'].str.replace(',', '').astype(float)
            df['買賣超張數'] = df['三大法人買賣超股數'] / 1000
            return df[['證券代號', '證券名稱', '買賣超張數']]
    except Exception:
        pass
    return pd.DataFrame()

def check_retail_leaving(stock_id):
    """使用 FinMind API 檢查散戶是否退場 (1-50張的持有總人數是否減少)"""
    url = "https://api.finmindtrade.com/api/v4/data"
    parameter = {
        "dataset": "TaiwanStockHoldingSharesPer",
        "data_id": stock_id,
        "start_date": (datetime.date.today() - datetime.timedelta(days=21)).strftime("%Y-%m-%d"),
        "token": FINMIND_TOKEN
    }
    try:
        res = requests.get(url, params=parameter)
        data = res.json()
        if data["status"] == 200 and len(data["data"]) > 0:
            df = pd.DataFrame(data["data"])
            # 取最近兩週的日期
            dates = df['date'].unique()[-2:]
            if len(dates) < 2: return True # 資料不足預設通過

            # 定義散戶：持股分級 1~5 (1股到50張)
            retail_df = df[df['HoldingSharesLevel'].isin([1,2,3,4,5])]
            last_week_retail = retail_df[retail_df['date'] == dates[0]]['people'].sum()
            this_week_retail = retail_df[retail_df['date'] == dates[1]]['people'].sum()

            return this_week_retail < last_week_retail
    except Exception:
        pass
    return True # API失敗時預設放行，以免錯失標的

def analyze_tw_stocks():
    msg = "🇹🇼 **【台股｜主力籌碼嚴選】**\n"
    recent_days = get_twse_dates(CONSECUTIVE_DAYS)
    today_str = recent_days[-1].strftime("%Y%m%d")

    today_data = get_twse_buy(today_str)
    if today_data.empty:
        return msg + "今日台股無資料或尚未更新。\n\n"

    top_5 = today_data.sort_values(by='買賣超張數', ascending=False).head(5)
    candidates = top_5['證券代號'].tolist()
    found = False

    for stock_id in candidates:
        stock_name = top_5[top_5['證券代號'] == stock_id]['證券名稱'].values[0]

        # 1. 散戶過濾
        if not check_retail_leaving(stock_id): continue

        # 2. 連續買超與成本過濾
        buy_vols, prices = [], []
        hist = yf.Ticker(f"{stock_id}.TW").history(period="10d")

        for date in recent_days:
            date_str = date.strftime("%Y%m%d")
            daily = get_twse_buy(date_str)
            time.sleep(2) # 防封鎖

            vol = daily[daily['證券代號'] == stock_id]['買賣超張數'].values[0] if (not daily.empty and stock_id in daily['證券代號'].values) else 0
            buy_vols.append(vol)

            try:
                price = hist.loc[date.strftime("%Y-%m-%d")]['Close']
                prices.append(price)
            except:
                prices.append(0)

        # 檢查遞增
        if any(buy_vols[i] <= buy_vols[i-1] for i in range(1, len(buy_vols))) or any(v <= 0 for v in buy_vols):
            continue

        total_vol = sum(buy_vols)
        avg_cost = sum(v * p for v, p in zip(buy_vols, prices) if p > 0) / total_vol if total_vol > 0 else 0
        curr_price = prices[-1] if prices else 0

        if curr_price > avg_cost * MAX_COST_DEVIATION: continue

        found = True
        msg += f"🎯 **{stock_id} {stock_name}**\n"
        msg += f"🔹 連續 {CONSECUTIVE_DAYS} 日買超遞增\n"
        msg += f"🔹 主力均價: {avg_cost:.2f} | 現價: {curr_price:.2f}\n"
        msg += f"🔹 籌碼狀態: 散戶退場中 ✅\n---\n"

    if not found: msg += "今日無符合【籌碼遞增+未追高+散戶退場】之嚴格標的。\n\n"
    return msg + "\n"

# ================= 美股分析模組 =================
def analyze_us_stocks():
    msg = "🇺🇸 **【美股｜價量潛力雷達】**\n*(美股無每日籌碼，改採價量突破與均線多頭過濾)*\n"
    # 監控重點科技與半導體巨頭 (可自行增刪)
    us_tickers = ["AAPL", "MSFT", "NVDA", "TSLA", "AMD", "META", "GOOGL", "AMZN", "PLTR", "ARM"]
    found = False

    for ticker in us_tickers:
        stock = yf.Ticker(ticker)
        hist = stock.history(period="1mo")
        if len(hist) < 20: continue

        curr_price = hist['Close'].iloc[-1]
        ma_20 = hist['Close'].rolling(window=20).mean().iloc[-1]
        curr_vol = hist['Volume'].iloc[-1]
        avg_vol = hist['Volume'].rolling(window=20).mean().iloc[-1]

        # 條件：站上月線 (MA20) 且 今日成交量大於月均量 1.5 倍 (主力介入跡象)
        if curr_price > ma_20 and curr_vol > avg_vol * 1.5:
            found = True
            msg += f"🚀 **{ticker}**\n"
            msg += f"🔸 現價: ${curr_price:.2f} (站上月線)\n"
            msg += f"🔸 爆量突破: 達均量 {(curr_vol/avg_vol):.1f} 倍\n---\n"

    if not found: msg += "今日重點觀測股無明顯價量突破跡象。\n"
    return msg

# ================= 主程式 =================
if __name__ == "__main__":
    final_msg = "📊 **每日盤後市場雷達** 📊\n==================\n\n"
    final_msg += analyze_tw_stocks()
    final_msg += analyze_us_stocks()
    send_telegram_message(final_msg)